.
.
.
new line...
before learning DevOps tools you have to learn Linux Command as well as Shellscript...
it is very important...
and I have to practice and practice untill n unless got the good job/company....
