hello everyone...
.
I hope you all are happy.....
.
Now,I have done the merging between master branch and development branch...
.
master ---> development
.
--> git merge development...
.
Also understand hoe to switch from one branch to other...
.
--> git checkout bn --> command to switching the commands.....
