hello everyone...
I hope you all are happy.....
master ---> development
--> git merge development...
Also understand hoe to switch from one branch to other...
--> git checkout bn --> command to switching the commands.....
hello....I'm from dev branch... 
If you want a good job, you have to do hardwork....
  
